# -*- coding: utf-8 -*-
"""data_descriptor_Chenyu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BH-134j_dhHR8628_ABD5jj6Rhb4qPZg

**Revise the form and calculate correlations of factors**
"""

ico = pd.read_csv('file1.csv')
ico1 = ico.set_index('ICO_Name')
ico1

enter_cmc = ico1['Enter_CMC'].values
max_cmc = ico1['Max_CMC'].values
min_cmc = ico1['Min_CMC'].values
ico_Price = ico1['ICO_Price'].values
total_Supply_Ratio = ico1['Total_Supply_Ratio'].values
ico_Market_Cap = ico1['ICO_Market_Cap'].values

"""Calculate the correlation """

import math
def de_mean(x):
    a = sum(x) / len(x)
    x_bar = a
    return [x_i - x_bar for x_i in x]
def dot(v, w):
    return sum(v_i * w_i for v_i, w_i in zip(v, w))
def sum_of_squares(v):
    return dot(v, v)
def standard_deviation(x): 
    n = len(x)
    deviations = de_mean(x)
    a= sum_of_squares(deviations) / (n - 1)
    return math.sqrt(a)
def covariance(x, y):
    n = len(x)
    return dot(de_mean(x), de_mean(y)) / (n -1)
def correlation(x, y):
    stdev_x = standard_deviation(x)
    stdev_y = standard_deviation(y)
    if stdev_x > 0 and stdev_y > 0:
        return covariance(x, y) / stdev_x / stdev_y
    else:
        return 0

correlation(ico_Price, enter_cmc)

correlation(ico_Price, max_cmc)

"""**Add prices in CoinMarketCap now for further analysis**

Install the CoinMarketCap
"""

pip install python-coinmarketcap

import coinmarketcapapi
cmc = coinmarketcapapi.CoinMarketCapAPI("b33eb123-96c5-4f30-89ad-20c440765f6b")

"""Using listing_lastest() to get token prices now"""

data_listing = cmc.cryptocurrency_listings_latest()

import pandas as pd
name=[]
price=[]
date_add=[]
for i in range (100):
  n = data_listing.data[i]['name']
  p = data_listing.data[i]['quote']['USD']['price']
  d = data_listing.data[i]['date_added']
  name.append(n)
  price.append(p)
  date_add.append(d)

"""Generate the dataframe and combine it with the original dataframe"""

df = pd.DataFrame(price,name)
df1 = df.rename(columns = {0:'Now_CMC'})
df1['data_added']=date_add

ico2 = pd.read_csv('ML_ICO_Sheet.csv')
ico3 = ico.set_index('ICO_Name')
ico3

final = ico3.join(df1,how='outer')
final = final.drop(columns=['Ian_ICO_Grade','Team','Advisors','Idea','Prototype','Community','Security','Type','Audience'])
final

final.to_csv('final_data.csv')